# To add an additional team, simply add a top-level key with a list of associated GitHub user handles

core-team:
  - '@jcampbell'       # James Campbell
  - '@NathanFarmer'    # Nathan Farmer
  - '@Shinnnyshinshin' # Will Shin
  - '@Super-Tanner'    # Tanner Beam
  - '@alexsherstinsky' # Alex Sherstinsky
  - '@anthonyburdi'    # Anthony Burdi
  - '@cdkini'          # Chetan Kini
  - '@donaldheppner'   # Don Heppner
  - '@billdirks'       # Bill Dirks
  - '@Kilo59'          # Gabriel Gore

devrel:
  - '@AFineDayFor'     # Hannah Stokes
  - '@Rachel-Reverie'  # Rachel Reverie
  - '@austiezr'        # Austin Robinson
  - '@kenwade4'        # Ken Wade
  - '@kyleaton'        # Kyle Eaton
  - '@rdodev'          # Ruben Orduz
  - '@talagluck'       # Tal Gluck

cloud:
  - '@roblim'          # Rob Lim
