# This file allows our autolabeler action to label PR's based on the author's GitHub handle.
# To add an additional team, simply add a top-level key with a list of users.
# NOTE - this should be kept in sync with the GX org's teams

platform:
  - '@NathanFarmer'    # Nathan Farmer
  - '@alexsherstinsky' # Alex Sherstinsky
  - '@cdkini'          # Chetan Kini
  - '@billdirks'       # Bill Dirks
  - '@Kilo59'          # Gabriel Gore

dx:
  - '@Shinnnyshinshin' # Will Shin
  - '@anthonyburdi'    # Anthony Burdi
  - '@kenwade4'        # Ken Wade

devrel:
  - '@Rachel-Reverie'  # Rachel Reverie
  - '@austiezr'        # Austin Robinson
  - '@kyleaton'        # Kyle Eaton
  - '@rdodev'          # Ruben Orduz
  - '@talagluck'       # Tal Gluck

cloud:
  - '@roblim'          # Rob Lim
  - '@rreinoldsc'      # Robby Reinold
  - '@joshua-stauffer' # Josh Stauffer
  - '@dctalbot'        # David Talbot

# Aggregates a few different teams
core-team:
  # Mario
  - '@NathanFarmer'    # Nathan Farmer
  - '@alexsherstinsky' # Alex Sherstinsky
  - '@cdkini'          # Chetan Kini
  - '@billdirks'       # Bill Dirks
  - '@Kilo59'          # Gabriel Gore
  # Luigi
  - '@Shinnnyshinshin' # Will Shin
  - '@anthonyburdi'    # Anthony Burdi
  - '@kenwade4'        # Ken Wade
  # Misc
  - '@jcampbell'       # James Campbell
  - '@donaldheppner'   # Don Heppner
  - '@Super-Tanner'    # Tanner Beam
