# To add an additional team, simply add a top-level key with a list of users.
# NOTE - this should be kept in sync with the GX org's teams

devrel:
  - "@kyleaton" # Kyle Eaton
  - "@rachhouse" # Rachel House
  - "@r34ctor" # Nevin Tan

core:
  - "@DrewHoo" # Drew Hoover
  - "@Erin-GX" # Erin Kapp
  - "@Kilo59" # Gabriel Gore
  - "@NathanFarmer" # Nathan Farmer
  - "@Shinnnyshinshin" # Will Shin
  - "@Super-Tanner" # Tanner Beam
  - "@TrangPham" # Thu Pham
  - "@abegong" # Abe Gong
  - "@allensallinger" # Allen Sallinger
  - "@anthonyburdi" # Anthony Burdi
  - "@billdirks" # Bill Dirks
  - "@cdkini" # Chetan Kini
  - "@dctalbot" # David Talbot
  - "@donaldheppner" # Don Heppner
  - "@elenajdanova" # Elena Jdanova
  - "@jcampbell" # James Campbell
  - "@josectobar" # José Tobar
  - "@joshua-stauffer" # Josh Stauffer
  - "@joshzzheng" # Josh Zheng
  - "@lockettks" # Kim Mathieu
  - "@nicgrayson" # Nic Grayson
  - "@roblim" # Rob Lim
  - "@rreinoldsc" # Robby Reinold
  - "@sujensen" # Susan Jensen
  - "@tyler-hoffman" # Tyler Hoffman
  - "@wookasz" # Łukasz Lempart
  - "@annabarr" # Anna Barr
  - "@alena-hutchinson" # Alena Hutchinson

bot:
  - "@dependabot"
  - "@dependabot[bot]"
  - "@pre-commit-ci[bot]"
