"""Methods and classes that are not marked with the @public_api decorator but may appear in our public docs are listed here.

Over time this list should be driven to 0 by either adding the @public_api decorator and an appropriate docstring or
adding an exclude directive to docs/sphinx_api_docs_source/public_api_excludes.py
"""

import pathlib

from docs.sphinx_api_docs_source.printable_definition import PrintableDefinition

ITEMS_IGNORED_FROM_PUBLIC_API = [
    PrintableDefinition(
        file=pathlib.Path("great_expectations/_docs_decorators.py"), name="add"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/checkpoint/actions.py"), name="get"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/checkpoint/actions.py"), name="_run"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/checkpoint/actions.py"), name="run"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/checkpoint/actions.py"), name="update"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/checkpoint/checkpoint.py"),
        name="describe_dict",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/compatibility/not_imported.py"),
        name="is_version_greater_or_equal",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/compatibility/typing_extensions.py"),
        name="override",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/batch.py"), name="head"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/batch_definition.py"),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/core/expectation_diagnostics/expectation_doctor.py"
        ),
        name="print_diagnostic_checklist",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/core/expectation_diagnostics/expectation_doctor.py"
        ),
        name="run_diagnostics",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/expectation_suite.py"),
        name="add_expectation_configuration",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/expectation_suite.py"),
        name="remove_expectation",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/expectation_validation_result.py"),
        name="describe_dict",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/factory/factory.py"), name="add"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/factory/factory.py"), name="all"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/factory/factory.py"), name="get"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/metric_domain_types.py"),
        name="MetricDomainTypes",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/metric_function_types.py"),
        name="MetricPartialFunctionTypes",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/partitioners.py"),
        name="ColumnPartitionerMonthly",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/partitioners.py"),
        name="PartitionerColumnValue",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/yaml_handler.py"), name="YAMLHandler"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/yaml_handler.py"), name="dump"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/core/yaml_handler.py"), name="load"
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/abstract_data_context.py"
        ),
        name="add_store",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/abstract_data_context.py"
        ),
        name="delete_datasource",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/abstract_data_context.py"
        ),
        name="get_docs_sites_urls",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/abstract_data_context.py"
        ),
        name="get_validator",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/abstract_data_context.py"
        ),
        name="list_datasources",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/abstract_data_context.py"
        ),
        name="open_data_docs",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/context_factory.py"
        ),
        name="build_data_docs",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/context_factory.py"
        ),
        name="get_context",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/context_factory.py"
        ),
        name="get_docs_sites_urls",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/data_context/context_factory.py"
        ),
        name="get_validator",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/data_context_variables.py"),
        name="save",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/store/_store_backend.py"),
        name="add",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/store/_store_backend.py"),
        name="update",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/store/checkpoint_store.py"),
        name="CheckpointStore",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/store/expectations_store.py"
        ),
        name="ExpectationsStore",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/store/metric_store.py"),
        name="MetricStore",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/store/store.py"), name="add"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/store/store.py"),
        name="update",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/store/tuple_store_backend.py"
        ),
        name="TupleFilesystemStoreBackend",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/store/validation_definition_store.py"
        ),
        name="ValidationDefinitionStore",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/store/validation_results_store.py"
        ),
        name="ValidationResultsStore",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/data_context/types/base.py"),
        name="update",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/data_context/types/resource_identifiers.py"
        ),
        name="GXCloudIdentifier",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/config_str.py"),
        name="ConfigStr",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/dataframe_partitioners.py"
        ),
        name="columns",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/directory_asset.py"
        ),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/directory_asset.py"
        ),
        name="get_batch_parameters_keys",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/file_asset.py"
        ),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/file_asset.py"
        ),
        name="get_batch_parameters_keys",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/path_data_asset.py"
        ),
        name="get_batch",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_asset/path/path_data_asset.py"
        ),
        name="get_batch_parameters_keys",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/datasource/fluent/data_connector/batch_filter.py"
        ),
        name="validate",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/fabric.py"),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/fabric.py"),
        name="get_batch",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/invalid_datasource.py"),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/invalid_datasource.py"),
        name="get_asset",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/invalid_datasource.py"),
        name="get_batch",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/invalid_datasource.py"),
        name="get_batch_parameters_keys",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/pandas_datasource.py"),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/pandas_datasource.py"),
        name="get_batch",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/sources.py"),
        name="delete_datasource",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/spark_datasource.py"),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/spark_datasource.py"),
        name="get_batch",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/sql_datasource.py"),
        name="build_batch_request",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/datasource/fluent/sql_datasource.py"),
        name="get_batch",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/exceptions/exceptions.py"),
        name="DataContextError",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/exceptions/exceptions.py"),
        name="InvalidExpectationConfigurationError",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/execution_engine/execution_engine.py"),
        name="ExecutionEngine",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/execution_engine/execution_engine.py"),
        name="get_compute_domain",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/pandas_execution_engine.py"
        ),
        name="PandasExecutionEngine",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/pandas_execution_engine.py"
        ),
        name="get_compute_domain",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/sparkdf_execution_engine.py"
        ),
        name="SparkDFExecutionEngine",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/sparkdf_execution_engine.py"
        ),
        name="get_compute_domain",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/sqlalchemy_execution_engine.py"
        ),
        name="SqlAlchemyExecutionEngine",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/sqlalchemy_execution_engine.py"
        ),
        name="execute_query",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/execution_engine/sqlalchemy_execution_engine.py"
        ),
        name="get_compute_domain",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_kl_divergence_to_be_less_than.py"
        ),
        name="ExpectColumnKLDivergenceToBeLessThan",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_max_to_be_between.py"
        ),
        name="ExpectColumnMaxToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_mean_to_be_between.py"
        ),
        name="ExpectColumnMeanToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_median_to_be_between.py"
        ),
        name="ExpectColumnMedianToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_min_to_be_between.py"
        ),
        name="ExpectColumnMinToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_pair_values_a_to_be_greater_than_b.py"
        ),
        name="ExpectColumnPairValuesAToBeGreaterThanB",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_pair_values_to_be_equal.py"
        ),
        name="ExpectColumnPairValuesToBeEqual",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_proportion_of_non_null_values_to_be_between.py"
        ),
        name="ExpectColumnProportionOfNonNullValuesToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py"
        ),
        name="ExpectColumnProportionOfUniqueValuesToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_quantile_values_to_be_between.py"
        ),
        name="ExpectColumnQuantileValuesToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_to_exist.py"
        ),
        name="ExpectColumnToExist",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_unique_value_count_to_be_between.py"
        ),
        name="ExpectColumnUniqueValueCountToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_value_z_scores_to_be_less_than.py"
        ),
        name="ExpectColumnValueZScoresToBeLessThan",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_values_to_be_in_type_list.py"
        ),
        name="ExpectColumnValuesToBeInTypeList",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_values_to_be_null.py"
        ),
        name="ExpectColumnValuesToBeNull",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_values_to_be_of_type.py"
        ),
        name="ExpectColumnValuesToBeOfType",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_values_to_be_unique.py"
        ),
        name="ExpectColumnValuesToBeUnique",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py"
        ),
        name="ExpectColumnDistinctValuesToBeInSet",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_compound_columns_to_be_unique.py"
        ),
        name="ExpectCompoundColumnsToBeUnique",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_multicolumn_sum_to_equal.py"
        ),
        name="ExpectMulticolumnSumToEqual",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_query_results_to_match_comparison.py"
        ),
        name="ExpectQueryResultsToMatchComparison",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_select_column_values_to_be_unique_within_record.py"
        ),
        name="ExpectSelectColumnValuesToBeUniqueWithinRecord",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_column_count_to_be_between.py"
        ),
        name="ExpectTableColumnCountToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_column_count_to_equal.py"
        ),
        name="ExpectTableColumnCountToEqual",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_columns_to_match_ordered_list.py"
        ),
        name="ExpectTableColumnsToMatchOrderedList",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_columns_to_match_set.py"
        ),
        name="ExpectTableColumnsToMatchSet",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_row_count_to_be_between.py"
        ),
        name="ExpectTableRowCountToBeBetween",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_row_count_to_equal.py"
        ),
        name="ExpectTableRowCountToEqual",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/expect_table_row_count_to_equal_other_table.py"
        ),
        name="ExpectTableRowCountToEqualOtherTable",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/core/unexpected_rows_expectation.py"
        ),
        name="UnexpectedRowsExpectation",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/expectation.py"),
        name="ColumnAggregateExpectation",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/expectation.py"),
        name="ColumnMapExpectation",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/expectation.py"),
        name="UnexpectedRowsExpectation",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/expectation.py"),
        name="render_suite_parameter_string",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/expectation.py"),
        name="validate_configuration",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/expectation_configuration.py"
        ),
        name="ExpectationConfiguration",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/expectation_configuration.py"
        ),
        name="to_domain_obj",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/expectation_configuration.py"
        ),
        name="type",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/metrics/column_aggregate_metric_provider.py"
        ),
        name="ColumnAggregateMetricProvider",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/metrics/column_aggregate_metric_provider.py"
        ),
        name="column_aggregate_partial",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/metrics/column_aggregate_metric_provider.py"
        ),
        name="column_aggregate_value",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py"
        ),
        name="column",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/metrics/map_metric_provider/column_condition_partial.py"
        ),
        name="column_condition_partial",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/expectations/metrics/map_metric_provider/column_map_metric_provider.py"
        ),
        name="ColumnMapMetricProvider",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/metrics/metric_provider.py"),
        name="MetricProvider",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/metrics/metric_provider.py"),
        name="metric_partial",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/expectations/metrics/metric_provider.py"),
        name="metric_value",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/experimental/metric_repository/metric_retriever.py"
        ),
        name="get_validator",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/components.py"),
        name="CollapseContent",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/components.py"),
        name="RenderedStringTemplateContent",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/components.py"),
        name="RenderedTableContent",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/components.py"), name="validate"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/renderer/email_renderer.py"),
        name="EmailRenderer",
    ),
    PrintableDefinition(
        file=pathlib.Path(
            "great_expectations/render/renderer/microsoft_teams_renderer.py"
        ),
        name="MicrosoftTeamsRenderer",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/renderer/opsgenie_renderer.py"),
        name="OpsgenieRenderer",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/renderer/renderer.py"),
        name="renderer",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/renderer/site_builder.py"),
        name="DefaultSiteIndexBuilder",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/renderer/site_builder.py"),
        name="SiteBuilder",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/renderer/slack_renderer.py"),
        name="SlackRenderer",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/util.py"),
        name="handle_strict_min_max",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/util.py"), name="num_to_str"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/util.py"),
        name="parse_row_condition_string_pandas_engine",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/render/util.py"),
        name="substitute_none_for_missing",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/metric_configuration.py"),
        name="MetricConfiguration",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/metrics_calculator.py"),
        name="columns",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/validation_graph.py"),
        name="resolve",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/validator.py"), name="columns"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/validator.py"), name="head"
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/validator.py"),
        name="remove_expectation",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/validator.py"),
        name="save_expectation_suite",
    ),
    PrintableDefinition(
        file=pathlib.Path("great_expectations/validator/validator.py"), name="validate"
    ),
]
