#!/bin/bash

export GE_CLOUD_BASE_URL="https://api.dev.greatexpectations.io"
export GE_CLOUD_ORGANIZATION_ID="0ccac18e-7631-4bdd-8a42-3c35cce574c6"
export GE_CLOUD_ACCESS_TOKEN="6284c351faa74ee6bcfcc6cfede25aac"
