from great_expectations.datasource.fluent.data_asset.path.regex_asset import RegexDataAsset


class CSVAsset(RegexDataAsset): ...


class ExcelAsset(RegexDataAsset): ...


class JSONAsset(RegexDataAsset): ...


class ORCAsset(RegexDataAsset): ...


class ParquetAsset(RegexDataAsset): ...


class FeatherAsset(RegexDataAsset): ...


class FWFAsset(RegexDataAsset): ...


class HDFAsset(RegexDataAsset): ...


class HTMLAsset(RegexDataAsset): ...


class PickleAsset(RegexDataAsset): ...


class SASAsset(RegexDataAsset): ...


class SPSSAsset(RegexDataAsset): ...


class StataAsset(RegexDataAsset): ...


class XMLAsset(RegexDataAsset): ...
