from .data_connector import DataConnector
from .file_path_data_connector import FilePathDataConnector
from .filesystem_data_connector import FilesystemDataConnector
from .s3_data_connector import S3DataConnector

FILE_PATH_BATCH_SPEC_KEY = FilePathDataConnector.FILE_PATH_BATCH_SPEC_KEY
