#!/bin/bash

CHANGED_FILES=$(git diff HEAD origin/develop --name-only)
printf '%s\n' "[CHANGED FILES]" "${CHANGED_FILES[@]}" ""

pip install -e . > /dev/null 2>&1 # Necessary to get GE helper methods working for `trace_docs_deps.py`

DEPENDENCIES=$(python scripts/trace_docs_deps.py docs)
printf '%s\n' "[DEPENDENCIES]" "${DEPENDENCIES[@]}" ""

echo "Checking for file changes from 'great_expectations/' that impact 'docs/'..."
for FILE in ${DEPENDENCIES}; do
    if [[ ${CHANGED_FILES[@]} =~ $FILE ]]; then
        echo "Found change in local dependency:" $FILE
        echo "##vso[task.setvariable variable=DocsDependenciesChanged;isOutput=true]true"
    fi
done
