""" This script trains a Prophet model and saves it to a JSON file.

This model is used in example tests for Expectations in this library.
The training data is generated by the script in `contrib/time_series_expectations/assets/generate_test_time_series_data.py`.

It's a simple model with no seasonality, no changepoints, no trend, and no outliers.
The average value is about 100 and the standard deviation is about 1.

Note: this model is manually copied to the `expectations/` folder to support built-in tests for Expectation classes.
"""

import pandas as pd
from prophet import Prophet
from prophet.serialize import model_to_json

df = pd.read_csv(
    "data/daily__size_180__trend_0__weekly_seasonality_0__outliers_1000.csv"
)

m = Prophet(
    growth="flat",
    changepoints=[],
    daily_seasonality=False,
    weekly_seasonality=False,
    yearly_seasonality=False,
    interval_width=0.99,
)
m.fit(df)

model_json = model_to_json(m)
with open("models/example_prophet_date_model.json", "w") as f_:
    f_.write(model_json)
