parameters:
  vmImage: "" # Must be specified in primary YAML
  pythonVersion: ["3.9", "3.10", "3.11"]

jobs:
  - ${{ each pythonVersion in parameters.pythonVersion }}:
      - job:
        displayName: pip${{ pythonVersion }}
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: ${{ pythonVersion }}
            displayName: Use Python ${{ pythonVersion }}

          - script: |
              python -m pip install --upgrade pip
              pip install --pre great_expectations
            displayName: "Install Great Expectations"

          - script: |
              python -c "import great_expectations as gx; print('Successfully imported GX Version:', gx.__version__)"
              python -c "import great_expectations as gx; gx.get_context(mode='ephemeral')"
            displayName: "Confirm installation"
# TODO: This is turned off since we don't ship the 1.0 prerelease to conda. I've filed a ticket turn this back on
# TODO: when this is available for conda
#      - job:
#        displayName: conda${{ pythonVersion }}
#        steps:
#          - task: UsePythonVersion@0
#            inputs:
#              versionSpec: ${{ pythonVersion }}
#            displayName: Use Python ${{ pythonVersion }}
#
#          - bash: echo "##vso[task.prependpath]$CONDA/bin"
#            displayName: Add conda to PATH
#
#          - script: |
#              conda create --yes --name gx_dev
#            displayName: Create Anaconda environment
#
#          - script: |
#              source activate gx_dev
#              conda install --yes --name gx_dev -c conda-forge great-expectations
#            displayName: "Install Great Expectations"
#
#          - script: |
#              source activate gx_dev
#              python -c "import great_expectations as gx; print('Successfully imported GX Version:', gx.__version__)"
#              python -c "import great_expectations as gx; gx.get_context(mode='ephemeral')"
#            displayName: "Confirm installation"
