parameters:
  vmImage: '' # Must be specified in primary YAML
  pythonVersion: ["3.8", "3.9", "3.10"]

jobs:
  - ${{ each pythonVersion in parameters.pythonVersion }}:
    - job:
      displayName: pip${{ pythonVersion }}
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{ pythonVersion }}
          displayName: Use Python ${{ pythonVersion }}

        - script: |
            python -m pip install --upgrade pip
            pip install great_expectations
          displayName: 'Install Great Expectations'

        - script: |
            great_expectations --version
            great_expectations -y init --no-usage-stats
            python -c "import great_expectations as gx; print('Successfully imported GX Version:', gx.__version__)"
          displayName: 'Confirm installation'

    - job:
      displayName: conda${{ pythonVersion }}
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: ${{ pythonVersion }}
          displayName: Use Python ${{ pythonVersion }}

        - bash: echo "##vso[task.prependpath]$CONDA/bin"
          displayName: Add conda to PATH

        - script: |
            conda create --yes --name gx_dev
          displayName: Create Anaconda environment

        - script: |
            source activate gx_dev
            conda install --yes --name gx_dev -c conda-forge great-expectations
          displayName: 'Install Great Expectations'

        - script: |
            source activate gx_dev
            great_expectations --version
            great_expectations -y init --no-usage-stats
            python -c "import great_expectations as gx; print('Successfully imported GX Version:', gx.__version__)"
          displayName: 'Confirm installation'
