#!/bin/bash

# Build API docs then build docusaurus docs.
# Currently used in our netlify pipeline.
# Note: Will be modified to build API docs on latest tagged release.

echo "Installing dev dependencies"
pip install -c constraints-dev.txt -e ".[test]"

echo "Installing dev dependencies"
(cd docs/sphinx_api_docs_source; pip install -r requirements-dev-api-docs.txt)

echo "Building sphinx API docs."
(cd docs/sphinx_api_docs_source; invoke docs)

echo "Copying previous versions"
curl "https://superconductive-public.s3.us-east-2.amazonaws.com/oss_docs_versions.zip" -o "oss_docs_versions.zip"
unzip -o oss_docs_versions.zip -d .

echo "Building docusaurus docs."
yarn build
