#!/bin/bash

# Build API docs then build docusaurus docs.
# Currently used in our netlify pipeline.
# Note: Will be modified to build API docs on latest tagged release.

# Previous versions

# Get all versions starting without `v`
git tag | grep -E "(^[0-9]{1,}\.)+[0-9]{1,}" | sort -V

# Get versions <0.14.x where x is largest, check out and build docs
git tag | grep -E "^[0-9]{1,}\.13\.[0-9]{1,}" | sort -V | tail -1

# Get version 0.14.x where x is largest, check out and build docs
echo "Building docs for 0.14.x"
V14=$(git tag | grep -E "^[0-9]{1,}\.14\.[0-9]{1,}" | sort -V | tail -1)
echo "printing pwd"
pwd
echo "printing pwd"
mkdir build_dir_version_0_14_x
cd build_dir_version_0_14_x
# Do I need to clone the whole repo here instead of checkout?
# Might be safer to avoid node package conflicts?
git checkout $V14
yarn install
yarn build
mv build/ ../versioned_docs/version-$V14
cd ..
ls
pwd
echo "Done building docs for 0.14.x"


# Get version 0.15.x where x is largest, check out and build docs
V15=$(git tag | grep -E "^[0-9]{1,}\.15\.[0-9]{1,}" | sort -V | tail -1)
git checkout $V15
yarn install
# Current versions
echo "Installing dev dependencies"
pip install -c constraints-dev.txt -e ".[test]"

echo "Installing dev dependencies"
(cd docs/sphinx_api_docs_source; pip install -r requirements-dev-api-docs.txt)

echo "Building sphinx API docs."
(cd docs/sphinx_api_docs_source; invoke docs)

echo "Building docusaurus docs."
yarn build

# Future versions: automated or manual?
