#!/bin/bash

print_orange () {
    ORANGE='\033[38;5;208m'
    NC='\033[0m' # No Color
    echo -e "${ORANGE}$1${NC}"
}

print_orange_line () {
    print_orange "================================================================================"
}

print_orange_header () {
    print_orange_line
    print_orange "$1"
    print_orange_line
}

print_orange_header "Preparing to build docs..."
./prepare_to_build_docs

print_orange_header "Running yarn start to serve docs locally..."
yarn start
