#!/bin/bash

# Prepare earlier library versions for use in documentation.
# Run this after creating a new major or minor version after adding the missing
# version to this script and any version specific steps.

CURRENT_DIR=$(pwd)

echo -e "${ORANGE}Copying code referenced from previous versions${NC}"
# TODO: Load versions from versions.json and loop through instead of manual process here:
# TODO: What else needs to be copied? Static assets like images and css?
# Copy code referenced in docs from version 0.14.13
mkdir 0.14.13
cd 0.14.13
git clone https://github.com/great-expectations/great_expectations.git
cd great_expectations
REPO_DIR_0_14_13=$(pwd)
git checkout 0.14.13
git pull
mkdir -p "$CURRENT_DIR"/versioned_code/version-0.14.13
cp tests "$CURRENT_DIR"/versioned_code/version-0.14.13

echo -e "${ORANGE}Skipping building API docs for v0.14.13, they are included in the md files.${NC}"

yarn install
yarn docusaurus docs: version 0.14.13
cd ../..

# Copy code referenced in docs from version 0.15.50
mkdir 0.15.50
cd 0.15.50
git clone https://github.com/great-expectations/great_expectations.git
cd great_expectations
REPO_DIR_0_15_50=$(pwd)
git checkout 0.15.50
git pull
mkdir -p "$CURRENT_DIR"/versioned_code/version-0.15.50
cp tests "$CURRENT_DIR"/versioned_code/version-0.15.50

echo -e "${ORANGE}Installing Great Expectations library dev dependencies for v0.15.50.${NC}"
pip install -c constraints-dev.txt -e ".[test]"

echo -e "${ORANGE}Installing api docs dependencies for v0.15.50.${NC}"
(cd docs/sphinx_api_docs_source; pip install -r requirements-dev-api-docs.txt)

echo -e "${ORANGE}Building API docs for v0.15.50.${NC}"
(cd docs/sphinx_api_docs_source; invoke docs)

yarn install
yarn docusaurus docs: version 0.15.50
cd ../..

# ADD MORE VERSIONS HERE

# Update versioned code and docs
echo -e "${ORANGE}Updating links in versioned docs${NC}"
# TODO: Update links in versioned docs, use @site (first double check this works)
# TODO: This should also be checked for links to static assets as well.

echo -e "${ORANGE}Updating filepath in versioned docs${NC}"
# TODO: Update filepath in versioned docs if they are using the old linenumber style of file=<filepath>L<lineno>
# TODO: By adding the correct versioned_code filepath e.g. versioned_code/version-0.14.13/
# TODO: Use the file path of the doc in versioned_docs/version-<version_number>/ to determine what version number it is

echo -e "${ORANGE}Updating snippet names in versioned docs${NC}"
# TODO: Update snippet names in versioned docs if they are using the style of name="<snippet_name>"
# TODO: By prepending the version e.g. name="version-0.15.50<original_snippet_name>"
python prepare_prior_versions.py